config/routes.rb
Browser::Application.routes.draw do
  get "hub/view"

  resources :games
  resources :developers
  
  devise_for :users
  
  get '/hub' => 'hub#view'

  root :to => 'home#index'

end

app/models/developer.rb
class Developer < ActiveRecord::Base

end

app/models/game.rb
class Game < ActiveRecord::Base

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable, 
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/developers_controller.rb
class DevelopersController < ApplicationController

  # GET /deveopers/1
  def show
    @developer = Developer.find(params[:id])
  end
  
  def index
    @developers = Developer.all
  end
  
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  # GET /games
  def index
    @games = Game.all
  end

  # GET /games/1
  def show
    @game = Game.find(params[:id])
  end

  # GET /games/new
  def new
    @game = Game.new
  end

  # GET /games/1/edit
  def edit
    @game = Game.find(params[:id])
  end

  # POST /games
  def create
    @game = Game.new(params[:game])

    if @game.save
      redirect_to @game, notice: 'Game was successfully created.'
    else
      render action: "new"
    end
  end

  # PUT /games/1
  def update
    @game = Game.find(params[:id])

    if @game.update_attributes(params[:game])
      redirect_to @game, notice: 'Game was successfully updated.'
    else
      render action: "edit"
    end
  end


  # DELETE /games/1
  def destroy
    @game = Game.find(params[:id])
    @game.destroy

    redirect_to games_url
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/hub_controller.rb
class HubController < ApplicationController
  
  before_filter :authenticate_user!
  
  def view
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/hub_helper.rb
module HubHelper
end

app/views/developers/index.html.erb
<h1>Developers</h1>
<p>
	<% @developers.each do |dev| %>
		<%= link_to dev.name, developer_path(dev) %> <br>
	<% end %>
</p>

app/views/developers/show.html.erb
<div class="developer">
	<h1>Juri Alexejewitsch Gagarin</h1>
	<div class="fact-box">
		<%= image_tag 'gagarin.jpg', :alt => 'Juri Alexejewitsch Gagarin', :class => 'rounded portrait' %>
		<p>
			<strong>Website</strong>: <span class="forceWrap"><a href="#">http://de.wikipedia.org/wiki/Juri_Alexejewitsch_Gagarin</a></span><br />
			<strong>Twitter</strong>: @Boctok1
		</p>
		<p>
			<strong>Credits:</strong><br />
			<strong>Designer</strong>: My first pony game, My second pony game, <a href="#">Ponys going to Space</a><br />
			<strong>Programmer</strong>: Ponys going to Space<br />
			<strong>Special Thanks</strong>: From Russia with Love
		</p>
	</div>

	<div class="text">
		<p>
			Aute letterpress anim cred, twee tattooed pinterest nostrud placeat ea blog aesthetic. Etsy sint bushwick laborum portland, commodo scenester. Authentic magna pitchfork bushwick, aesthetic pour-over VHS flexitarian raw denim sustainable mixtape quis gastropub wolf. Chillwave seitan narwhal banh mi. Vegan fixie cardigan readymade swag marfa retro, godard freegan ad excepteur culpa commodo squid etsy. Excepteur mustache ex officia, quis raw denim voluptate bushwick. Pariatur stumptown post-ironic helvetica portland master cleanse.
		</p>
		<p>
			farm-to-table, authentic deserunt selvage whatever tofu biodiesel thundercats wayfarers chillwave typewriter brooklyn. Mumblecore bespoke officia authentic trust fund. Nostrud bushwick velit quis echo park Austin. Pickled salvia small batch, mustache banh mi pork belly cosby sweater four loko narwhal. Viral nostrud veniam, sunt keffiyeh craft beer trust fund shoreditch. Irure food truck selvage, sustainable irony readymade qui fingerstache pork belly tempor lomo exercitation veniam. Tumblr 8-bit direct trade, pariatur anim readymade iphone next level tempor beard.
		</p>
		<p>
			Ethnic VHS next level, eu readymade culpa iphone hella beard irony laboris banh mi art party assumenda. Qui cillum occaecat cray Austin sapiente bushwick, squid butcher synth art party next level sriracha proident forage. Mumblecore consequat artisan wes anderson, single-origin coffee occupy commodo whatever cray marfa eiusmod. Scenester locavore sriracha, before they sold out organic trust fund quis small batch tattooed PBR. Ethical ut quinoa shoreditch, pork belly freegan keffiyeh veniam stumptown culpa mcsweeney's mustache american apparel dreamcatcher. Cillum single-origin coffee anim incididunt cardigan artisan. Chambray sed sriracha reprehenderit.
		</p>
		<p>
			Ennui food truck adipisicing, vinyl high life seitan direct trade authentic. Freegan truffaut placeat, umami portland +1 cred nostrud. Trust fund locavore sunt, readymade viral art party aute skateboard PBR sriracha. Post-ironic quinoa fugiat pork belly tempor. Pariatur nulla shoreditch brooklyn, farm-to-table pork belly aute four loko. Sartorial ut nisi umami. Dolore direct trade gastropub master cleanse food truck laboris gentrify, umami ullamco.
		</p>
	</div>
	
	<div class="clear"></div>
</div>

<script>

$(document).ready(function() {
	var target = $('div.developer').offset().top - 25;
	
	$('html, body').animate({scrollTop: target}, 1000);
})

</script>

app/views/games/_form.html.erb
<%= form_for(@game) do |f| %>
  <% if @game.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@game.errors.count, "error") %> prohibited this game from being saved:</h2>

      <ul>
      <% @game.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/games/edit.html.erb
<h1>Editing game</h1>

<%= render 'form' %>

<%= link_to 'Show', @game %> |
<%= link_to 'Back', games_path %>

app/views/games/index.html.erb
<h1>Games</h1>


<a href="/games/1">
	<div class="grid_12 alpha omega tile">
		<%= image_tag('dummy_teaser.jpg', :class => 'rounded teaser')%>
		<div class="caption"><div>generic shooter game</div></div>
	</div>
</a>
<a href="/games/1">
	<div class="grid_12 alpha omega tile">
		<%= image_tag('dummy_teaser.jpg', :class => 'rounded teaser')%>
		<div class="caption"><div>generic shooter game</div></div>
	</div>
</a>

<a href="/games/1">
	<div class="grid_12 alpha omega tile">
		<%= image_tag('dummy_teaser.jpg', :class => 'rounded teaser')%>
		<div class="caption"><div>generic shooter game</div></div>
	</div>
</a>

<a href="/games/1">
	<div class="grid_12 alpha omega tile">
		<%= image_tag('dummy_teaser.jpg', :class => 'rounded teaser')%>
		<div class="caption"><div>generic shooter game</div></div>
	</div>
</a>

<div class="clear"></div>

<div class="pager">
	<span class="prev">Prev</span>
	<a href=""><span class="page">1</span></a>
	<span class="active">2</span>
	<a href=""><span>3</span></a>
	<a href=""><span >4</span></a>
	<a href=""><span>5</span></a>
	<a href=""><span>6666</span></a>
	<a href=""><span>...777</span></a>
	<a href=""><span class="next">Next</span></a>
</div>
		


<!-- <% @games.each do |game| %>
  <tr>
    <td><%= game.name %></td>
    <td><%= game.description %></td>
    <td><%= link_to 'Show', game %></td>
    <td><%= link_to 'Edit', edit_game_path(game) %></td>
    <td><%= link_to 'Destroy', game, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %> -->

<!-- <%= link_to 'New Game', new_game_path %> -->

app/views/games/new.html.erb
<h1>New game</h1>

<%= render 'form' %>

<%= link_to 'Back', games_path %>

app/views/games/show.html.erb
<div class="game">
	<div class="alpha omega teaser">
		<%= image_tag 'dummy_teaser.jpg', :alt => 'teaser screenshot', :class => 'rounded' %>
	</div>
	<h1>This is a Game Title</h1>
	
	<div class="fact-box">
		<p>
			<strong>Developer</strong>: <a href="#">Some developer</a><br />
			<strong>Released</strong>: 2012<br />
			<strong>Platforms</strong>: PC, Mac, Linux, XBox360, PS3<br />
			<strong>Publisher</strong>: <a href="#">Awesome game publisher</a><br />
		</p>

		<p>
			<strong>Design</strong>: Turenga Leela<br />
			<strong>Programming</strong>: <a href="#">Bender Bending Rodruigez</a><br />
			<strong>QA Lead</strong>: Scruffy<br />
			<strong>EMEA Publishing</strong>: Awesome Game Publisher<br />
			<strong>Localisation</strong>: Das Translation
		</p>

	</div>
	
	<div class="text">
		<p>
			Aute letterpress anim cred, twee tattooed pinterest nostrud placeat ea blog aesthetic. Etsy sint bushwick laborum portland, commodo scenester. Authentic magna pitchfork bushwick, aesthetic pour-over VHS flexitarian raw denim sustainable mixtape quis gastropub wolf. Chillwave seitan narwhal banh mi. Vegan fixie cardigan readymade swag marfa retro, godard freegan ad excepteur culpa commodo squid etsy. Excepteur mustache ex officia, quis raw denim voluptate bushwick. Pariatur stumptown post-ironic helvetica portland master cleanse.
		</p>
		<p>
			farm-to-table, authentic deserunt selvage whatever tofu biodiesel thundercats wayfarers chillwave typewriter brooklyn. Mumblecore bespoke officia authentic trust fund. Nostrud bushwick velit quis echo park Austin. Pickled salvia small batch, mustache banh mi pork belly cosby sweater four loko narwhal. Viral nostrud veniam, sunt keffiyeh craft beer trust fund shoreditch. Irure food truck selvage, sustainable irony readymade qui fingerstache pork belly tempor lomo exercitation veniam. Tumblr 8-bit direct trade, pariatur anim readymade iphone next level tempor beard.
		</p>
		<p>
			Ethnic VHS next level, eu readymade culpa iphone hella beard irony laboris banh mi art party assumenda. Qui cillum occaecat cray Austin sapiente bushwick, squid butcher synth art party next level sriracha proident forage. Mumblecore consequat artisan wes anderson, single-origin coffee occupy commodo whatever cray marfa eiusmod. Scenester locavore sriracha, before they sold out organic trust fund quis small batch tattooed PBR. Ethical ut quinoa shoreditch, pork belly freegan keffiyeh veniam stumptown culpa mcsweeney's mustache american apparel dreamcatcher. Cillum single-origin coffee anim incididunt cardigan artisan. Chambray sed sriracha reprehenderit.
		</p>
		<p>
			Ennui food truck adipisicing, vinyl high life seitan direct trade authentic. Freegan truffaut placeat, umami portland +1 cred nostrud. Trust fund locavore sunt, readymade viral art party aute skateboard PBR sriracha. Post-ironic quinoa fugiat pork belly tempor. Pariatur nulla shoreditch brooklyn, farm-to-table pork belly aute four loko. Sartorial ut nisi umami. Dolore direct trade gastropub master cleanse food truck laboris gentrify, umami ullamco.
		</p>
	</div>
	
	<div class="clear"></div>
	
	<div class="media rounded">
		<%= image_tag 'screenshot_1.jpg', :alt => 'Screenshot 1 alt text' %>
		<div class="caption">
			This is an image caption for this very screenshot
		</div>
	</div>
	
	<div class="media rounded">
		<%= image_tag 'screenshot_2.jpg', :alt => 'Screenshot 2 alt text' %>
		<div class="caption">
			This is an image caption for this very screenshot
		</div>
	</div>
</div>

<script>

$(document).ready(function() {
	var target = $('div.game').offset().top - 25;
	
	$('html, body').animate({scrollTop: target}, 1000);
})

</script>

<!-- <%= link_to 'Edit', edit_game_path(@game) %> |
<%= link_to 'Back', games_path %> -->

app/views/home/index.html.erb
<div>
	<h1>About us</h1>
	<p>Lomo sriracha farm-to-table, authentic deserunt selvage whatever tofu biodiesel thundercats wayfarers chillwave typewriter brooklyn. Mumblecore bespoke officia authentic trust fund. Nostrud bushwick velit quis echo park Austin. Pickled salvia small batch, mustache banh mi pork belly cosby sweater four loko narwhal.</p>
	<div class="more"><a href="#">more...</a></div>
</div>

<div>
	<h1>News</h1>
	<p><strong>September 3rd, 2012</strong> &mdash; Lomo sriracha farm-to-table, authentic deserunt selvage whatever tofu biodiesel thundercats wayfarers chillwave typewriter brooklyn. Mumblecore bespoke officia authentic trust fund. Nostrud bushwick velit quis echo park Austin. Pickled salvia small batch, mustache banh mi pork belly cosby sweater four loko narwhal.</p>
	<div class="more"><a href = "#">more...</a></div>
</div>

<div>
	<h1><%= link_to 'Games', games_path %></h1>
	<div class="tiled_2x">
		<a href="/games/1">
			<div class="tile">
				<%= image_tag('dummy_teaser.jpg', :class => 'rounded teaser')%>
				<div class="caption"><div>This is a game</div></div>
			</div>
		</a>
	</div>
	
	<div class="tiled_2x">
		<a href="/games/1">
			<div class="tile">
				<%= image_tag('dummy_teaser.jpg', :class => 'rounded teaser')%>
				<div class="caption"><div>This is a game</div></div>
			</div>
		</a>
	</div>
	
	<div class="tiled_2x">
		<a href="/games/1">
			<div class="tile">
				<%= image_tag('dummy_teaser.jpg', :class => 'rounded teaser')%>
				<div class="caption"><div>This is a game</div></div>
			</div>
		</a>
	</div>
	
	<div class="tiled_2x">
		<a href="/games/1">
			<div class="tile">
				<%= image_tag('dummy_teaser.jpg', :class => 'rounded teaser')%>
				<div class="caption"><div>This is a game</div></div>
			</div>
		</a>
	</div>
	
	<div class="tiled_2x">
		<a href="/games/1">
			<div class="tile">
				<%= image_tag('dummy_teaser.jpg', :class => 'rounded teaser')%>
				<div class="caption"><div>This is a game</div></div>
			</div>
		</a>
	</div>
	
	<div class="clear"></div>
	<div class="more"><%= link_to 'more...', games_path %></div>
</div>

<div>
	<h1><%= link_to 'People', developers_path %></h1>

	<div class="tiled_4x">
		<a href="/developers/1">
			<div class="tile" >
				<%= image_tag('gagarin.jpg', :class => 'rounded teaser')%>
				<div class="caption"><div>Juri Alexejewitsch Gagarin</div></div>
			</div>
		</a>
	</div>
	
	<div class="tiled_4x">
		<a href="/developers/1">
			<div class="tile" >
				<%= image_tag('gagarin.jpg', :class => 'rounded teaser')%>
				<div class="caption"><div>Juri Alexejewitsch Gagarin</div></div>
			</div>
		</a>
	</div>
	
	<div class="tiled_4x">
		<a href="/developers/1">
			<div class="tile" >
				<%= image_tag('gagarin.jpg', :class => 'rounded teaser')%>
				<div class="caption"><div>Juri Alexejewitsch Gagarin</div></div>
			</div>
		</a>
	</div>
	
	<div class="tiled_4x">
		<a href="/developers/1">
			<div class="tile" >
				<%= image_tag('gagarin.jpg', :class => 'rounded teaser')%>
				<div class="caption"><div>Juri Alexejewitsch Gagarin</div></div>
			</div>
		</a>
	</div>
	
	<div class="tiled_4x">
		<a href="/developers/1">
			<div class="tile" >
				<%= image_tag('gagarin.jpg', :class => 'rounded teaser')%>
				<div class="caption"><div>Juri Alexejewitsch Gagarin</div></div>
			</div>
		</a>
	</div>
	
	<div class="tiled_4x">
		<a href="/developers/1">
			<div class="tile" >
				<%= image_tag('gagarin.jpg', :class => 'rounded teaser')%>
				<div class="caption"><div>Juri Alexejewitsch Gagarin</div></div>
			</div>
		</a>
	</div>

	<div class="tiled_4x">
		<a href="/developers/1">
			<div class="tile" >
				<%= image_tag('gagarin.jpg', :class => 'rounded teaser')%>
				<div class="caption"><div>Juri Alexejewitsch Gagarin</div></div>
			</div>
		</a>
	</div>
	
	<div class="tiled_4x">
		<a href="/developers/1">
			<div class="tile" >
				<%= image_tag('gagarin.jpg', :class => 'rounded teaser')%>
				<div class="caption"><div>Juri Alexejewitsch Gagarin</div></div>
			</div>
		</a>
	</div>
	
	<div class="clear"></div>
	<div class="more"><%= link_to 'more...', developers_path %></div>
</div>

app/views/hub/view.html.erb
<h1>Welcome to the hub</h1>
<p><%= link_to "account settings", edit_user_registration_path %> </p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  	<title>Browser</title>
	<link href='http://fonts.googleapis.com/css?family=Bitter:400,700&amp;subset=latin,latin-ext' rel='stylesheet' type='text/css'>
  	<%= stylesheet_link_tag    "application", :media => "all" %>
  	<%= javascript_include_tag "application" %>
  	<%= csrf_meta_tags %>
</head>
<body>
	
<div class="notice"><%= notice %></div>
<div class="alert"><%= alert %></div>

<div id="responsiveHelper"><span>media type: </span></div>

<div id="header">
	<div class="container">
		<div class="logo">
			<a href="/">
				<%= image_tag'logo.svg' %>
			</a>
		</div>
		<div class="brief">
			<p>Lomo sriracha farm-to-table, authentic deserunt selvage whatever tofu biodiesel thundercats wayfarers chillwave typewriter brooklyn. Mumblecore bespoke officia authentic trust fund. Nostrud bushwick velit quis echo park Austin. Pickled salvia small batch, mustache banh mi pork belly cosby sweater four loko narwhal. </p>
		</div>
	
		<div class="clear"></div>
	
		<div class="menu">
			<ul>
				<li>home</li>
				<li>about us</li>
				<li>news</li>
				<li>press</li>
			</ul>
			<ul>
				<li>games</li>
				<li>people</li>
				<li>companies*</li>
			</ul>
			<ul>
				<li>search</li>
			</ul>
			<ul>
				<li>sign in</li>
				<li>sign up</li>
			</ul>
		</div>	
		<div class="clear"></div>
	</div>
</div>


<!-- <div>
	<% if user_signed_in? %>
		signed in as <strong><%= link_to current_user.email, hub_path %></strong> | 
		<%= link_to "sign out", destroy_user_session_path, :method => :delete %>
	<% else %>
		<%= link_to "sign in", new_user_session_path %> | 
		<%= link_to "sign up", new_user_registration_path %>
	<% end %>
</div> -->


<div id="body">
	<div class="container">
		<%= yield %>
	</div>
</div>

<div id="footer">
	<div class="container">
		<div class="menu">
			<ul>
				<li>home</li>
				<li>about us</li>
				<li>news</li>
				<li>press</li>
			</ul>
			<ul>
				<li>games</li>
				<li>people</li>
				<li>companies*</li>
			</ul>
			<ul>
				<li>search</li>
			</ul>
			<ul>
				<li>sign in</li>
				<li>sign up</li>
			</ul>
		</div>
		
		<div class="clear"></div>
		
		<div id="legal" class="grid_12">
			<p>Ennui food truck adipisicing, vinyl high life seitan direct trade authentic. Freegan truffaut placeat, umami portland +1 cred nostrud. Trust fund locavore sunt, readymade viral art party aute skateboard PBR sriracha. Post-ironic quinoa fugiat pork belly tempor.</p>
			<p>
				(c) 2012, some rights reserved
			</p>
		</div>
		
		<div class="clear"></div>
		<div id="footerLogo" class="grid_2">

			<%= image_tag 'logo-grey.svg' %>
		</div>
	</div>
</div>				

</body>
</html>